### ISSUE TITLE
Lost connection to relays popup

### ISSUE THREAD

**Issue by thebullishbitcoiner** [supertestnet/superstore#8]
The attached popup keeps popping up. I’ve tried refreshing the browser and using the website on a fresh install of Firefox. 
![Screenshot 2023-07-14 234136](https://github.com/supertestnet/superstore/assets/139607837/056a2a13-1164-494f-bc10-aa005612d629)

**Comment by time-out** [comment]
Yes, it happens all the time.

**Comment by supertestnet** [comment]
I think it is because one of the relays I hard coded, wss://relay.wellorder.net, is no longer functional. You can adjust your relays by these steps:

- Go to your store's admin page
- Your relays are in your url
- Swap out relay.wellorder.net with some other relay from this list: https://nostr.watch/
- Hit enter so that the page reloads with your new set of relays
- Resubmit your store so that the update propagates to the frontend of your store
- If you've used your "old" url anywhere it will still have your "old" set of relays in it so update all public links to your store so that they contain the new url (containing your new set of relays)

I have also upgraded the site to replace relay.wellorder.net with relay.damus.io as a default

**Comment by thebullishbitcoiner** [comment]
That works! Thanks! 🤙🏼

**Comment by GALLAY** [comment]
Does not work for me. Popup appears regularly.
![wss](https://github.com/supertestnet/superstore/assets/7523322/49f7db1b-33c6-4a14-804a-0b21612203b1)
![lost](https://github.com/supertestnet/superstore/assets/7523322/49e44672-1ca7-4b50-be17-4c97a3b48c03)

**Comment by thebullishbitcoiner** [comment]
Hm I noticed that sometimes too, even after editing the relays. I wonder if it's a coincidence that a relay doesn't respond when polled. So theoretically, even if a relay is "good", it could fail the connection check at any time for whatever reason. Just my guess. 😄

**Comment by supertestnet** [comment]
It looks like the new culprit is wss://nostr.oxtr.dev/ -- they are no longer reliable. I have replaced them as a default with wss://nostr.zenon.info. I also updated the alert message, which now does several things:

(1) it tells you which relay is giving you trouble
(2) it tries to detect if you are the store admin or just a customer
(3) if it thinks you are just a customer it tells you to please ask the store admin for assistance if the connection issue persists
(4) if it thinks you are the store admin it tells you how to update your relays and directs you to this github if you need further assistance

I hope these efforts remedy the issue.

**Comment by supertestnet** [comment]
I modified the relay logic in the following ways:

- for buyers, it tries to detect to at least 2 relays on pageload. If that works, it will not show them any connection errors
- for sellers, before it shows a connection error it tries to reconnect to whatever relay went down, and it only shows an error if it can't reconnect in 5 seconds

For these reasons I do not think connection errors are likely to be displayed anymore except when a relay really is down. So I think this problem is finally solved and am closing this issue.
